version: '3'
services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitmq_untitled8
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER = user
      - RABBITMQ_DEFAULT_PASSWORD = user